### ISSUE TITLE
JOSS: Add tests and CI/CD

### ISSUE THREAD

**Issue by engnadeau** [klevis-a/kinematics-vis#12]
- Tests can be used for both CI/CD and for new users to ensure they properly installed the repo
- Tests should be based on example datasets that should also be provided
- Tests should be run for all PRs to ensure quality
- If this repo will be used by "biomechanics researchers and clinicians with a limited mathematical background", we'll need to guide them properly
- cc https://github.com/openjournals/joss-reviews/issues/3490

**Comment by klevis-a** [comment]
Per our discussion in openjournals/joss-reviews/#3490 added manual test cases in https://github.com/klevis-a/kinematics-vis/commit/cdd7dfb7187f948c60f479761c9c99f0692e5543.

**Comment by engnadeau** [comment]
@klevis-a 

- would it be possible to make these changes in PRs for easier review and traditional git flow? 
- where are sample files from?

**Comment by klevis-a** [comment]
@nnadeau

* Are you referring to all the issues that you opened (and are now closed)? If so, yes I can create PRs for these.
* The sample files (hosted at the University of Utah Center for High Performance Computing) are downloaded via the downloadData scripts. The dataset was collected in our lab. It was published alongside "Beyond Euler/Cardan angles: True Axial Rotation..." in [Zenodo](https://zenodo.org/record/4536684). However, the dataset downloaded via the downloadData scripts is not identical to the one on Zenodo because it conforms to the format specification of the webapp.

**Comment by engnadeau** [comment]
yeah, i was referring to all the commits made. Ideally, the commits aren't made directly to `master`, but rather a PR is created per issue (or batch of issues). I.e., PRs should close issues, not direct commits.

**Comment by klevis-a** [comment]
@nnadeau I initially thought that PRs could also be made retroactively between any commits - but that's not the case. It seems that PRs can only be made between two branches. I'll keep that in mind moving forward. I'm not sure what to do about the prior commits. There might be a way to make them into PRs but it won't be straightforward.
