### ISSUE TITLE
JOSS: Can not load test data

### ISSUE THREAD

**Issue by destogl** [klevis-a/kinematics-vis#14]
openjournals/joss-reviews#3490

**Describe the bug**
When trying to open any test data, "File not found" error happens.
Using `master` branch.

Hint about error: It appears that the selected data in the web browser are not filled correctly when trying to access them.

**To Reproduce**
1. Install as per README, download dependencies and data using scripts.
2. Start python server as per README
3. open localhost:8000/man.html

**Expected behavior**
Test data should be shown in the view, instead "Loading..." is forever on the scrren.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Firefox 91.0.2; Chromium 93.0.4577.63

**Additional context**
Terminal output: 
```
127.0.0.1 - - [13/Sep/2021 11:45:53] code 404, message File not found
127.0.0.1 - - [13/Sep/2021 11:45:53] "GET /csv/undefined HTTP/1.1" 404 -
127.0.0.1 - - [13/Sep/2021 11:45:53] code 404, message File not found
127.0.0.1 - - [13/Sep/2021 11:45:53] "GET /csv/undefined HTTP/1.1" 404 -
```

Under `csv` folder, I can see the data.

**Comment by klevis-a** [comment]
@destogl sorry about that. During the review process I made changes to the master branch in order to simplify data specification. I updated the live link dataset, but forgot to update the test data dataset. Really they are the same thing, but the test data is a zipped version for easy downloading. I simply forgot to update the zip file. This update is done now - no code changes needed. Please test it out. You can simply delete your current csv directory and run ./downloadData.sh again.

**Comment by destogl** [comment]
It works! Thanks!
