### ISSUE TITLE
JOSS: Consolidate default branch

### ISSUE THREAD

**Issue by destogl** [klevis-a/kinematics-vis#15]
As per #14 it seems that `master` branch is not working, but `joss` does. Before finalizing the review, I think branches should be consolidated and the default branch a user is checking out has to function properly. There are multiple options to resolve this:

- Make `joss` branch default (and maybe remove `master` branch)
- Merge `joss` into master.

cc. openjournals/joss-reviews#3490

**Comment by klevis-a** [comment]
@destogl the issue that you ran into with #14 was due to me not having updated the test dataset. All code changes that I have made during the review have been to master - that is the branch that is the most up to date. The joss branch is simply there to contain the paper. And I believe this is fine, according to the JoOS instructions.
