### ISSUE TITLE
JOSS: Novelty of repo

### ISSUE THREAD

**Issue by engnadeau** [klevis-a/kinematics-vis#8]
- Visualization and providing tools is great, but **why** should a researcher use this particular repo?
- "biomechanics researchers and clinicians [may have] a limited mathematical background", but we're assuming that they're skilled enough to use github and run shell scripts
- Why wouldn't they program their own simple visualizer? `three.js` is super popular and supported, why not create a simple visualizer for just your exact need?
- Why would a researcher depend on an external repo? Each external tool or dependency that's used carries its own risk; is this repo worth the risk?
- Has this repo been used in published research to prove its novelty and robustness?
- cc https://github.com/openjournals/joss-reviews/issues/3490

**Comment by klevis-a** [comment]
@nnadeau see https://github.com/klevis-a/kinematics-vis/commit/6dc0d8a522589cb835b86a5b44789657b21eea5e. I'm happy to create Pull Requests for these, if that's easier for you.

**Comment by klevis-a** [comment]
@nnadeau sorry, the aforementioned commit doesn't address this issue. It addresses another one, please ignore.

**Comment by klevis-a** [comment]
Hmm, now I wonder if the aforementioned commit does address these concerns as well. Please let me know. These are my thoughts regarding your comments.

1. The gap between creating 3D visualization/animations using three.js and going to github and running a shell script is very wide, in my opinion. The former requires knowledge of JavaScript, HTML, CSS, three.js, and 3D rotations (which are notoriously confusing). The latter is under the knowledge domain of most researchers. However, I do agree that modifying the code in order create custom functionality will require knowledge of JavaScript, three.js, etc. However, at that time this repo provides a decent starting base for researchers.

2. This repo does not create a code dependency (i.e. it is designed to be utilized as a standalone utility). The only downside that I see is that dependencies need to be downloaded via a shell script. However, if someone wants to circumvent this - it's easy enough to download the dependencies manually. They total under 10 files.

**Comment by engnadeau** [comment]
Thanks for adding the section. Has this repo been used in published research to demonstrate its novelty?

**Comment by klevis-a** [comment]
It has been utilized in our publication titled "Beyond Euler/Cardan Analysis: True Axial Rotation...". However, at the time I could not cite the repo because it was under review at the technology transfer office (PIVOT). We have received positive feedback from it at a recent conference and from other colleagues. I think it's very useful from a learning perspective. As far as I can tell, there's no other tool in biomechanics that visualizes decompositions (plenty of them will visualize the motion of the bones).

I could understand how you would think that a tool like this should exist already, but the unfortunately reality is that it doesn't. I would not have created this utility otherwise.
